CREATE OR ALTER PROCEDURE CreateTables
AS
BEGIN

CREATE TABLE Users (
	UserID INT PRIMARY KEY IDENTITY(1, 1),
	Username VARCHAR(32) NOT NULL,
	Mail VARCHAR(255) NOT NULL,
	Password VARCHAR(255) NOT NULL,
	Role VARCHAR(255),	-- Patient, Doctor, Admin
	Name VARCHAR(255) NOT NULL,
	Birthdate DATE NOT NULL,
	Cnp VARCHAR(13) NOT NULL,
	Address VARCHAR(255) NOT NULL,
	PhoneNumber VARCHAR(10) NOT NULL,
	RegistrationDate DATETIME NOT NULL,
);

CREATE TABLE Admins (
	AdminID INT PRIMARY KEY IDENTITY(1, 1),
	UserID INT FOREIGN KEY REFERENCES Users(UserID) ON DELETE CASCADE,
);

CREATE TABLE Departments (
	DepartmentID INT PRIMARY KEY IDENTITY(1, 1),
	Name VARCHAR(255) NOT NULL,
);

CREATE TABLE Doctors (
	DoctorID INT PRIMARY KEY IDENTITY(1, 1),
	UserId INT FOREIGN KEY REFERENCES Users(UserID) ON DELETE CASCADE UNIQUE,
	Experience FLOAT,
	Rating FLOAT,
	DepartmentId INT FOREIGN KEY REFERENCES Departments(DepartmentID) ON DELETE CASCADE,
	LicenseNumber VARCHAR(255) NOT NULL,
);

CREATE TABLE Drugs (
	DrugID INT PRIMARY KEY IDENTITY(1, 1),
	Name VARCHAR(255) NOT NULL,
	Administration VARCHAR(255) NOT NULL,
	Supply INT,
	Specification VARCHAR(255) NOT NULL,
);

CREATE TABLE Equipments (
	EquipmentID INT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
	Name VARCHAR(255) NOT NULL,
	Specification VARCHAR(255) NOT NULL,
	Type VARCHAR(255) NOT NULL,
	Stock INT,
);

CREATE TABLE Rooms (
	RoomID INT PRIMARY KEY IDENTITY(1, 1),
	Capacity INT,
	DepartmentID INT FOREIGN KEY REFERENCES Departments(DepartmentID) ON DELETE CASCADE,
	EquipmentID INT FOREIGN KEY REFERENCES Equipments(EquipmentID) ON DELETE SET NULL, -- equipment is optional
);

CREATE TABLE Shifts (
	ShiftID INT PRIMARY KEY IDENTITY(1, 1),
	Date DATE NOT NULL,
	StartTime TIME NOT NULL,
	EndTime TIME NOT NULL,
);

CREATE TABLE Schedules (
	ScheduleID INT PRIMARY KEY IDENTITY(1, 1),
	DoctorID INT FOREIGN KEY REFERENCES Doctors(DoctorID) ON DELETE CASCADE,
	ShiftID INT FOREIGN KEY REFERENCES Shifts(ShiftID) ON DELETE CASCADE,
);

CREATE TABLE Reviews (
	ReviewID INT PRIMARY KEY IDENTITY (1, 1),
	NrStars INT NOT NULL,
	Text VARCHAR(MAX),
	MedicalRecordID INT,
	-- MedicalRecordID INT PRIMARY PRIMARY KEY,
	-- FOREIGN KEY (MedicalRecordID) REFERENCES MedicalRecords(MedicalRecordID) ON DELETE CASCADE
);

END;