USE HospitalManagement;
GO

CREATE OR ALTER PROCEDURE DropTables
AS
BEGIN

DROP TABLE IF EXISTS Schedules;
DROP TABLE IF EXISTS Shifts;
DROP TABLE IF EXISTS Rooms;
DROP TABLE IF EXISTS Equipments;
DROP TABLE IF EXISTS Drugs;
DROP TABLE IF EXISTS Doctors;
DROP TABLE IF EXISTS Departments;
DROP TABLE IF EXISTS Admins;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Reviews;

END;