# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      Solution_Name: Duo.Api/Duo.Api.sln
      Project_Path: Duo.Api/Duo.Api.csproj
      Test_Project_Path: Duo.Api.Tests/Duo.Api.Tests.csproj

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore $Project_Path
    - name: Build
      run: dotnet build $Project_Path --no-restore
    - name: Test
      run: dotnet test $Test_Project_Path --no-build --verbosity normal
